language: cpp
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - protobuf-compiler
    - libprotobuf-dev
    - libgl-dev
    - libglew-dev
    - libcairo2-dev
    - libpango1.0-dev
    - libgtkmm-3.0-dev
    - libboost-dev
    - libglu1-mesa-dev

before_script:
  - sudo -E add-apt-repository -y 'deb http://ftp.us.debian.org/debian unstable main contrib non-free'
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes libglfw3-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99

script:
  - ./autogen.sh
  - ./configure
  - make -j4 distcheck || (cat remy-0.1/_build/src/tests/test-suite.log && exit 1)

notifications:
  slack: keithw:pcPsG04nsEuSMDabFhPDOyYq
